### ISSUE TITLE
Use of ReconnectingClientFactory

### ISSUE THREAD

**Issue by arunc84** [dpnova/txmemcache#2]
I am planning to use txmemcache in one of my projects and I have a question regarding reconnection functionality of txmemcache.
As I see in the code, MemCacheClientFactory lacks the functionality of reconnecting to memcache server if the connection drops. This connection drop can be due to any reason such as rebooting of memcache server machine, overload etc.
I was wondering whether you are planning to add this functionality in future version or have you done some work related to that?
If not, I would like to work on this problem.
Thanks
Arun

**Comment by dpnova** [comment]
Hey, I looked at it, but ended up not needing this library. I think it does reconnect, it's bee a while since I've looked at the code. I originally forked it from https://code.launchpad.net/tx.memcache/ so it may have been updated more recently there.

Sorry I'm not more help.. pretty irresponsible of me :P
